ALTER TABLE gevu_logements 
ADD Type_Logement VARCHAR( 10 ) NOT NULL ,
ADD Code_Escalier VARCHAR( 10 ) NOT NULL ,
ADD Etage VARCHAR( 10 ) NOT NULL ,
ADD Exposition VARCHAR( 10 ) NOT NULL ,
ADD Nombre_pieces int(11) NOT NULL ,
ADD Surface_Reelle DECIMAL( 10, 2 ) NOT NULL ,
ADD Surface_Appliquee DECIMAL( 10, 2 ) NOT NULL ,
ADD Type_Reception_TV VARCHAR( 10 ) NOT NULL ,
ADD Categorie_Module VARCHAR( 10 ) NOT NULL ,
ADD CREP_Date datetime NOT NULL ,
ADD CREP_presence_Plomb VARCHAR( 10 ) NOT NULL ,
ADD CREP_Seuil_Plomb_depasse VARCHAR( 10 ) NOT NULL ,
ADD DTA_Date datetime NOT NULL ,
ADD DTA_Date_Travaux datetime NOT NULL ,
ADD DTA_Presence_Amiante VARCHAR( 10 ) NOT NULL ,
ADD DTA_Presence_Amiante_Degradee VARCHAR( 10 ) NOT NULL ,
ADD DTA_Mesure_Conservatoire VARCHAR( 10 ) NOT NULL,
ADD DPE_Date VARCHAR( 10 ) NOT NULL,
ADD DPE_consommation_reelle int(11) NOT NULL,
ADD DPE_Categorie_Consommation VARCHAR( 10 ) NOT NULL,
ADD DPE_emissions_GES int(11) NOT NULL,
ADD DPE_Categorie_Emissions_GES VARCHAR( 10 ) NOT NULL;

UPDATE gevu_logements l JOIN gevu_stats s ON s.id_lieu = l.id_lieu
SET 
  l.Code_Escalier = s.Code_Escalier, 
  l.Categorie_Module = s.Categorie_Module, 
  l.Type_Logement = s.Type_Logement, 
  l.Nombre_pieces = s.Nombre_pieces, 
  l.Etage = s.Etage, 
  l.Surface_Reelle = s.Surface_Reelle, 
  l.Surface_Appliquee = s.Surface_Appliquee,
  l.maj = NOW(),
  l.Type_Reception_TV = s.Type_Reception_TV,
  l.DPE_Date = STR_TO_DATE(s.DPE_Date,'%d/%m/%Y %H:%i'), 
  l.DPE_consommation_reelle = s.DPE_consommation_reelle, 
  l.DPE_Categorie_Consommation = s.DPE_Categorie_Consommation, 
  l.DPE_emissions_GES = s.DPE_emissions_GES, 
  l.DPE_Categorie_Emissions_GES = s.DPE_Categorie_Emissions_GES, 
  l.CREP_Date = STR_TO_DATE(s.CREP_Date,'%d/%m/%Y %H:%i'), 
  l.CREP_presence_Plomb = s.CREP_presence_Plomb, 
  l.CREP_Seuil_Plomb_depasse = s.CREP_Seuil_Plomb_depasse, 
  l.DTA_Date = STR_TO_DATE(s.DTA_Date,'%d/%m/%Y %H:%i'), 
  l.DTA_Presence_Amiante = s.DTA_Presence_Amiante, 
  l.DTA_Presence_Amiante_Degradee = s.DTA_Presence_Amiante_Degradee, 
  l.DTA_Mesure_Conservatoire = s.DTA_Mesure_Conservatoire, 
  l.DTA_Date_Travaux = STR_TO_DATE(s.DTA_Date_Travaux,'%d/%m/%Y %H:%i');


