<?php
	if($this->json){
		echo json_encode($this->stats);
		return ;
	}
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<title>GEVU : statistiques disponibles</title>
</head>
<body>
<h1>Statistiques disponibles</h1>
<?php
	$niv = "";
	foreach($this->stats as $s){
		if($niv!=$s[0]){
			echo "<h2>".$s[0]."</h2>";
			$niv=$s[0];
		}
		echo "<a href='".$s[2]."'><h3>".$s[1]."</h3></a>"; 
	}
?>
</body>
</html>	
	