<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
    <title>GEVU : Antennes - données générale - Typologie logement</title>
	<link rel="stylesheet" href="../js/colorbrewer/colorbrewer.css" />
    <script type="text/javascript" src="../js/d3.v2.js"></script>
    <script type="text/javascript" src="../js/colorbrewer/colorbrewer.js"></script>
    <link type="text/css" rel="stylesheet" href="../css/button.css"/>
  </head>
  <body>
<legend align="center"><big><u>Antennes - données générales - Typologie logement</u></big></Legend><br><br>
    <div>
		<?php
			$i=0;
			$arrTL = $this->typesLog;
			$script = "";
			foreach($this->typesLog as $tl){
				//$class = "active last";
				//if($i=="0")$class = "first";
				$class = "first";
				echo "<button id='".$tl["code"]."' class='".$class."'>".$tl["titre"]."</button>";
				$script .= '
					d3.select("#'.$tl["code"].'").on("click", function() {
			   			getTypeLog("'.$tl["code"].'");
					';
				foreach($arrTL as $TL){
					if($tl["code"]==$TL["code"]) $script .= 'd3.select("#'.$tl["code"].'").classed("active", true);
						';
					else $script .= 'd3.select("#'.$TL["code"].'").classed("active", false);
						';
				}	
			    $script .= ' });
			    	';
				$i ++; 
			}
		?>
		<p/>
    </div>
    <table>
    	<tr>
    		<td><div id="chart" ></div></td>
    		<td><div id="legende" ></div></td>
    	</tr>
    </table>
    <script type="text/javascript" src="../js/partition.js"></script>
    <script type="text/javascript" >
	getLegende();
    
	<?php echo $script; ?>
    	
    </script>
    
  </body>
</html>
